routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','SmsController@index');
Route::resource('sms','SmsController');
Route::get('sms/send/{id}','SmsController@send');
Route::get('sms/report/{file}','SmsController@report');

app/sms.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class sms extends Model
{
    //
}

app/Http/Controllers/SmsController.php
<?php

namespace App\Http\Controllers;

use App\sms;
use Illuminate\Http\Request;
// use App\AfricasTalkingGateway as MyGateway;

class SmsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $texts= sms::all();
        return view('web.sms.index',compact('texts'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('web.sms.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
         // dd(request()->all());

        $sms= new sms;
         $this->validate($request, [
        'phone_number' => 'required|numeric',
        'text_message' => 'required|min:10',
        ]);

         $phone_number=Self::cleanTxt($request->phone_number);
         $text_message=Self::cleanTxt($request->text_message);
         echo strlen($phone_number);
         $sms->phone_number=$phone_number;
         $sms->text_message=$text_message;
         $sms->save();
         if($sms)
         {
            return redirect("/sms/".$sms->id)->with('success', 'Sms has been created, proced to send sms');
         }
         else{
            return redirect('/sms')->with('error', 'Try again an error occured.');
         }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\sms  $sms
     * @return \Illuminate\Http\Response
     */
    public function show($id=null)
    {
        //
        $text= sms::find($id);
        return view('web.sms.view',compact('text'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\sms  $sms
     * @return \Illuminate\Http\Response
     */
    public function edit(sms $sms)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\sms  $sms
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, sms $sms)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\sms  $sms
     * @return \Illuminate\Http\Response
     */
    public function destroy(sms $sms)
    {
        //
    }

    public function report($file)
    {
        return response()->download(storage_path("../uploads/{$file}"));
    }

    public function send($id=null)
    {
         $sms= sms::find($id);  

         if($sms->status==1)
         {
            return redirect("/sms/".$sms->id)->with('success', 'Sms has been sent to '.$sms->phone_number);
         }
         else{
            Self::smsGateway($sms->phone_number,$sms->text_message,$sms->id);
         }
          return redirect()->back();
    }

    public function smsGateway($phone_number,$text_message,$id)
    {
 $sms= sms::find($id);       
require_once('AfricasTalkingGateway.php');
// Specify your authentication credentials
$username   = "int";
$apikey     = "bd2785794bd83efd62fa397bd5da9299ce594455d3b8180fdb36698ec1ed9bc2";
// Specify the numbers that you want to send to in a comma-separated list
// Please ensure you include the country code (+254 for Kenya in this case)
$recipients ="+".$phone_number;
// And of course we want our recipients to know what we really do
$message    = strip_tags(trim($text_message));
// Create a new instance of our awesome gateway class

$url="https://api.africastalking.com/restless/send?username=int&Apikey=bd2785794bd83efd62fa397bd5da9299ce594455d3b8180fdb36698ec1ed9bc2&to=$recipients&message=".urlencode($message);

// exit();
$filename = $url;
$ch = curl_init();
curl_setopt ($ch, CURLOPT_URL, $filename);
curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1);
$contents = curl_exec($ch);
curl_close($ch);

$searchWord ="Success";
$searchWord = preg_quote($searchWord);

if (strpos($contents,$searchWord) !== false) {
    $sms->status="1";
     $sms->status_message="success";
     $sms->save();
}
else{

    $sms->status="2";
     $sms->status_message="Failed";
     $sms->save();
}

    }

    public function cleanTxt($str=null)
    {
        $str=filter_var(trim($str),FILTER_SANITIZE_STRING);
        return $str;
    }
}

resources/views/web/sms/create.blade.php
@extends('layouts.web')
@section('content')
<h2>Compose Sms</h2>
  @include('web.error')
 <div class="form-horizontal">
 	<form action="{{route('sms.store')}}" method="POST">
 		{{ csrf_field() }}
 				<div class="form-group">
			<h4>Phone Number </h4>
			<input type="text" name="phone_number" placeholder="2547XXXXXXXX" value="{{old('phone_number')}}">
		</div>

		<div class="form-group">
			<h4>Message</h4>
			<textarea name="text_message" cols="50" rows="6">{{old('text_message')}}</textarea>
		</div>

		

		<div class="form-group">
			<div class="col-sm-10 col-sm-offset-2">
				<button type="submit" class="btn btn-default btn-md"><i class="fa fa-pencil" aria-hidden="true"></i> Compose</button>
			</div>
		</div> 
	</form>                       		
</div>                           
@stop

resources/views/web/sms/edit.blade.php
@extends('layouts.web')

@section('content')

<h2>edit Sms</h2>
@stop

resources/views/web/sms/index.blade.php
@extends('layouts.web')

@section('content')
 @include('web.error')
<?php if(!$texts->IsEmpty()):
$html='<table class="table table-hover">
					<thead>
						<tr>
							<th width="30%">Phone Number</th>
							<th width="10%">Status</th>
						</tr>
					</thead>
					<tbody>';
foreach($texts as $text):
$html.="<tr><td>$text->phone_number</td><td>$text->status_message</td></tr>";
endforeach;	
$html.="</tbody></table>";
endif;
$ft=time()."record.xls";
$file="../uploads/$ft";
$myfile = fopen($file, "w") or die("Unable to open file!");
$txt = $html;
fwrite($myfile, $txt);
fclose($myfile);
?>
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<a href="<?php echo url("sms/create"); ?>" class="pull-right">
			<button class="btn btn-default"><i class="fa fa-plus" aria-hidden="true"></i> New Sms</button>
		</a>
		<a href="<?php echo url("sms/report/$ft"); ?>" class="pull-left">
			<button class="btn btn-default"><i class="fa fa-file-excel-o" aria-hidden="true"></i> Report</button>
			</a>
	</div>
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		@if(!$texts->IsEmpty()):
			<div class="table-responsive">
				<table class="table table-hover">
					<thead>
						<tr>
							<th width="10%">Phone Number</th>
							<th width="10%">Status</th>
							<th width="10%">Date</th>
							<th width="20%">&nbsp;</th>
						</tr>
					</thead>
					<tbody>
						
				
			</div>
			@foreach($texts as $text)
			<tr>
							<td>{{$text->phone_number }}</td>
							<td>{{$text->status_message }}</td>
							<td>{{$text->created_at }}</td>
							<td>
							@if($text->status==null)	
								<a href="{{url("sms/send/$text->id")}}"><button class="btn btn-default"><i class="fa fa-paper-plane" aria-hidden="true"></i> Send Message</button></a>
							@endif	
								<a href="{{url("sms/$text->id")}}"><button class="btn btn-default"><i class="fa fa-chevron-right" aria-hidden="true"></i> Details</button></a>
							</td>
						</tr>
			@endforeach
				</tbody>
				</table>
		@else
		<h3>There are no texts at the moment.</h3>
		@endif
	</div>
</div>
@stop 

resources/views/web/sms/view.blade.php
@extends('layouts.web')

@section('content')
  @include('web.error')
<h2>&rarr;Sms Details</h2>

<h4 class="txt-bold">Phone Number </h4>
<p>{{ $text->phone_number}}</p>
<h4 class="txt-bold">Message</h4>
<p>{{ $text->text_message}}</p>

<h4 class="txt-bold">Status : 
@if($text->status==1)
	Message Sent
@elseif($text->status==null)
	Message Pending
@elseif($text->status==2)
	Message Failed to send

@endif
</h4>
<a href="{{url("sms/send/$text->id")}}"><button class="btn btn-default"><i class="fa fa-paper-plane" aria-hidden="true"></i> Send Message</button></a>
@stop